### ISSUE TITLE
Could not install pypiwin32

### ISSUE THREAD

**Issue by qjqjqjj** [Skuldur/facenet-face-recognition#7]
Hi,

While I was installing the modules that is needed in requirements.txt. I could install pypiwin32, I tried sudo pip3 install pypiwin32 but it shows this error:

Collecting pywin32
  Could not find a version that satisfies the requirement pywin32 (from versions: )
No matching distribution found for pywin32

Does anyone know how to solve this?

**Comment by Niraj-Lunavat** [comment]
Hello 
I am also facing this same issue....did you install it

**Comment by Niraj-Lunavat** [comment]
Finally i solved it using command
sudo pip install pypiwin32==219

**Comment by aajap** [comment]
> Finally i solved it using command
> sudo pip install pypiwin32==219

Collecting pypiwin32==219
  Downloading https://files.pythonhosted.org/packages/2b/ca/5c086c18de8f70222787b3e824e755b68d99272531522e77bb381d4f60c8/pypiwin32-219.zip (4.8MB)
    100% |████████████████████████████████| 4.8MB 200kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ztp90dx_/pypiwin32/setup.py", line 121
        print "Building pywin32", pywin32_version
                               ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Building pywin32", pywin32_version)?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ztp90dx_/pypiwin32/

**Comment by aajap** [comment]
@qjqjqjj how do you solve it?
